### ISSUE TITLE
AttributeError: 'result' object has no attribute 'id'

### ISSUE THREAD

**Issue by Ewetoye** [blakev/Flask-WhooshAlchemy3#10]
When searching, no error is thrown if the search does not produce result, but when results are available, *flask-whoshalchemy3* throws an AttributeError as shown below
```
Traceback (most recent call last):
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Equimolar/EquimolarBlog/equimolar_blog/views.py", line 191, in search
    results = pub_article.search(q).paginate(1)
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 501, in paginate
    total = self.order_by(None).count()
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3776, in count
    return self.from_self(col).scalar()
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3496, in scalar
    ret = self.one()
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "/usr/local/Equimolar/eq_env/lib/python3.8/site-packages/flask_whooshalchemy/__init__.py", line 70, in __iter__
    str_pk = str(getattr(row, self._pk))
AttributeError: 'result' object has no attribute 'id'
```

**Comment by Eliasmgprado** [comment]
This BUG was reported and corrected in other versions of Flask-whooshalchemy [here](https://github.com/gyllstromk/Flask-WhooshAlchemy/pull/14/commits/98e5d4714035272d32a18af5e5dcd2f3367da72f).

I created a pull request implementing the needed modifications. 
#12
